/* Generated by Omarchy template substitution from colors.toml */

@define_color accent {{ accent }};
@define_color cursor {{ cursor }};
@define_color foreground {{ foreground }};
@define_color background {{ background }};
@define_color selection_foreground {{ selection_foreground }};
@define_color selection_background {{ selection_background }};

@define_color active_border_color {{ active_border_color }};
@define_color active_tab_background {{ active_tab_background }};

@define_color color0 {{ color0 }};
@define_color color1 {{ color1 }};
@define_color color2 {{ color2 }};
@define_color color3 {{ color3 }};
@define_color color4 {{ color4 }};
@define_color color5 {{ color5 }};
@define_color color6 {{ color6 }};
@define_color color7 {{ color7 }};
@define_color color8 {{ color8 }};
@define_color color9 {{ color9 }};
@define_color color10 {{ color10 }};
@define_color color11 {{ color11 }};
@define_color color12 {{ color12 }};
@define_color color13 {{ color13 }};
@define_color color14 {{ color14 }};
@define_color color15 {{ color15 }};
