/*
 * Project: oldjobobo-custom-omarchy-templates
 * Template: waybar.css.tpl
 * Version: 0.1.5
 * Author: OldJobobo
 * Generated by: Omarchy template substitution
 * Source: colors.toml + colors.css
 */

@import url("colors.css");

@define-color foreground {{ color15 }};
@define-color background {{ color0 }};
